// GENERATED by pipeline/beatgrid_to_ts.py — do not hand-edit.
// Source: audio/analysis/digital-lemonade (120.2 BPM, beat confidence 0.81).
// Shot lengths are measured from the track's actual detected beat times, not
// from a nominal 15f grid, so the edit cannot drift against the music.

export const MUSIC = {
  file: "digital-lemonade.mp3",
  credit:
    '"Digital Lemonade" by Kevin MacLeod (incompetech.com) — CC BY 4.0. ' +
    "Attribution required.",
  bpm: 120.2,
  beatConfidence: 0.81,
  /** where in the ORIGINAL track our window starts, in seconds */
  sourceStartSec: 127.3034,
  /** the window sits on the quiet bars before the track's strongest passage */
  sourceSection: "breakdown(3 bars) → main(7 bars, energy 0.813) → outro",
} as const;

/** Beats per shot — the edit's rhythmic intent, independent of tempo. */
export const SHOT_BEATS = [3, 5, 2, 4, 5, 6, 4, 3, 4, 3, 4, 3, 6];

/** Cut positions in frames, relative to the film start (length 53). */
export const CUT_FRAMES = [0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 329, 344, 359, 374, 389, 404, 419, 434, 449, 464, 479, 494, 509, 524, 539, 554, 569, 584, 599, 614, 629, 644, 659, 674, 689, 704, 719, 734, 749, 764, 779];

/** Shot durations in frames, derived from CUT_FRAMES. */
export const BEAT_DURATIONS = [45, 75, 30, 60, 75, 89, 60, 45, 60, 45, 60, 45, 90];

export const FILM_FRAMES = 779;
