// GENERATED by pipeline/set_music.py — do not hand-edit.
// Source: digital-lemonade.mp3 (120.2 BPM, beat confidence 0.81)
// Shot lengths are measured from this track's ACTUAL detected beat times, not
// from a nominal grid, so the edit cannot drift against the music.

export const MUSIC = {
  file: "digital-lemonade.mp3",
  credit: "\"Digital Lemonade\" by Kevin MacLeod (incompetech.com) \u2014 CC BY 4.0. Attribution required.",
  bpm: 120.19,
  beatConfidence: 0.81,
  /** where in the ORIGINAL track this window starts, in seconds */
  sourceStartSec: 127.5156,
  sourceSection: "--at 127.3s",
} as const;

/**
 * One beat in frames. Shot-internal animation keyframes must be multiples of
 * this (or clean halves of it), otherwise reveals land a few frames behind the
 * music even though the cuts themselves are on the beat — which reads as the
 * whole film being slightly out of sync.
 */
export const BEAT_F = 14.98;
/** Snap a beat count to whole frames: b(1) = one beat, b(0.5) = half a beat. */
export const b = (beats: number) => Math.round(beats * BEAT_F);

/** Beats per shot — the edit's rhythmic intent, independent of tempo. */
export const SHOT_BEATS = [5, 2, 4, 5, 6, 4, 3, 5, 4, 6, 4, 6];

/** Cut positions in frames, relative to film start (length 55). */
export const CUT_FRAMES = [0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 329, 344, 359, 374, 389, 404, 419, 434, 449, 464, 479, 494, 509, 524, 539, 554, 569, 584, 599, 614, 629, 644, 659, 674, 689, 704, 719, 734, 749, 764, 779, 794, 809];

/** Shot durations in frames, derived from CUT_FRAMES. */
export const BEAT_DURATIONS = [75, 30, 60, 75, 89, 60, 45, 75, 60, 90, 60, 90];

export const FILM_FRAMES = 809;

/**
 * Ducking gains, derived from THIS track's own dynamics rather than hand-tuned.
 * The music already supplies 1.6 dB of open→body contrast, so the
 * envelope only makes up the difference to 15 dB.
 */
export const DUCK = {"open": 0.214, "preRise": 0.364, "dip": 0.096, "body": 1.0, "outro": 0.34} as const;
