#!/usr/bin/env python3
"""
Stitch pipeline/vocab-parts/*.md into one canonical MOVE_VOCAB.v2.md.

The reconciliation is split across four agents by pattern family, because a
single agent trying to emit ~100 moves in one file blew the 64k output limit.
Each part contributes its family tables plus Aliases / Conflicts / Dropped
sections scoped to its own families; this merges them and carries the easing
reference over from MOVE_VOCAB.md verbatim, since that part is already canonical.

  python3 pipeline/assemble_vocab.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARTS = sorted((ROOT / "pipeline/vocab-parts").glob("*.md"))
OUT = ROOT / "pipeline/MOVE_VOCAB.md"
SECTIONS = ("Aliases", "Conflicts", "Dropped")

HEADER = """# Move vocabulary — canonical

One name per mechanism. GENERATED by `pipeline/assemble_vocab.py` — edit
`MOVE_VOCAB.base.md` (the primitives) or `pipeline/vocab-parts/*.md` (the families)
and re-run it, not this file.

It exists because the vocabulary had fragmented into three overlapping sources: the
original ~45 primitives, ~25 later shape-masking proposals, and ~169 `new_moves:`
proposals written independently across 47 reference specs by authors who could not
see each other's work. Duplicates under different names were certain, and a model
reading all three got contradictory vocabularies with no precedence. Both earlier
files are now retired into this one.

**Precedence, in order:**

1. A name already in the original `MOVE_VOCAB.md` wins for the same mechanism.
2. Otherwise the clearest of the competing proposals wins.
3. A move already implemented in `video/src/moves/` keeps its exported name.

When a future spec proposes a name for something already here, add it to the
Aliases table rather than renaming the canonical entry — the 47 existing specs
still contain the old names and have to stay interpretable.

**`status` column:** `built: ExportName` means it exists in `video/src/moves/`
and can be imported today. `spec-only` means it is described precisely enough to
build but has not been built — expect a spec citing it not to compile.

**Two moves that look like duplicates and are not.** These recur, so they are
called out up front:

- `motionTrail` offsets echoes in **time** (2f apart). `holoEchoOutline` offsets
  them in **scale and hue**, perfectly time-synced. Same idea, different mechanism.
- `orbitRing` **rotates continuously** as ambient. `radialCluster` places items
  **statically** with per-item idle and staggers their arrival. Same geometry,
  opposite intent.

---
"""


# Sections of the original MOVE_VOCAB.md that must survive verbatim. The twelve
# PATTERNS.md families describe COMPOSITIONAL patterns, so the base primitives —
# entrances, exits, camera, treatment, and the timing law — belong to none of them
# and were silently dropped by every family agent. Assembling without this carried
# 27 moves off a cliff, including maskWipeUp, pushIn, scaleIn, staggerRise and
# typeOn, all of which are built and in use.
CARRY = [
    "Easing names used throughout",
    "Entrance moves",
    "Exit moves",
    "Continuous / ambient moves",
    "Camera moves (applied to the whole composition)",
    "Transitions between shots",
    "Treatment layers",
    "Timing law (non-negotiable)",
]


def carried_sections() -> str:
    """Pull the primitive sections out of MOVE_VOCAB.md unchanged."""
    src = (ROOT / "pipeline/MOVE_VOCAB.base.md").read_text()
    out = []
    for title in CARRY:
        m = re.search(rf"^(## {re.escape(title)}[^\n]*\n.*?)(?=^## |\Z)", src, re.M | re.S)
        if m:
            out.append(m.group(1).rstrip())
        else:
            print(f"  !! could not carry section: {title}", file=sys.stderr)
    return "\n\n".join(out)


def built_index() -> str:
    """
    Map every move name to its exported component, read from the code.

    The primitive tables are carried verbatim and therefore have no `status`
    column, so 32 built components were invisible to a reader of Part 1. Generated
    rather than written by hand so it cannot drift from the source.
    """
    exported = set()
    for f in sorted((ROOT / "video/src/moves").glob("*.ts*")):
        exported |= set(re.findall(r"^export const ([A-Z][A-Za-z0-9]*)", f.read_text(), re.M))

    text = (ROOT / "pipeline/MOVE_VOCAB.base.md").read_text()
    rows = []
    for name in sorted(set(re.findall(r"^\|\s*`([a-zA-Z][A-Za-z0-9]*)`", text, re.M))):
        hit = next((e for e in exported if e.lower() == name.lower()), None)
        rows.append(f"| `{name}` | {'`' + hit + '`' if hit else '— not built'} |")
    unmapped = sorted(e for e in exported
                      if e.lower() not in {n.lower() for n in
                                           re.findall(r"^\|\s*`([a-zA-Z][A-Za-z0-9]*)`", text, re.M)})
    extra = ""
    if unmapped:
        extra = ("\n\nBuilt components that are NOT primitives (they belong to the pattern "
                 "families in Part 2): " + ", ".join(f"`{u}`" for u in unmapped) + ".")
    return ("## Which primitives are built\n\nGenerated from `video/src/moves/` — import these "
            "directly.\n\n| move | component |\n|---|---|\n" + "\n".join(rows) + extra + "\n")


def split_part(text: str):
    """Return (family_body, {section_name: rows}) for one part file."""
    idx = len(text)
    for name in SECTIONS:
        m = re.search(rf"^### {name}\b.*$", text, re.M)
        if m:
            idx = min(idx, m.start())
    families = text[:idx].rstrip()

    found = {}
    for name in SECTIONS:
        m = re.search(rf"^### {name}\b[^\n]*\n(.*?)(?=^### |\Z)", text, re.M | re.S)
        if m:
            rows = [
                ln for ln in m.group(1).strip().splitlines()
                # keep data rows only; headers and separators are re-emitted once
                if ln.strip().startswith("|") and not re.match(r"^\|[\s:|-]+\|$", ln.strip())
            ]
            # drop a repeated header row if the agent included one
            if rows and re.search(r"\|\s*(proposed\b|move\s*A\b|proposal\b)", rows[0], re.I):
                rows = rows[1:]
            found[name] = rows
    return families, found


def family_sort_key(body: str):
    m = re.search(r"^## (\d+)\.(\d+)", body, re.M)
    return (int(m.group(1)), int(m.group(2))) if m else (99, 99)


def main():
    if not PARTS:
        sys.exit("no parts in pipeline/vocab-parts/ — run the reconciliation agents first")

    bodies, merged = [], {k: [] for k in SECTIONS}
    for p in PARTS:
        fam, secs = split_part(p.read_text())
        # one part file may carry several families; keep them together, sort later
        bodies.append(fam)
        for k, rows in secs.items():
            merged[k].extend(rows)

    bodies.sort(key=family_sort_key)

    heads = {
        "Aliases": ("Every proposed name that was folded away, and what it maps to. The 47 "
                    "specs still use these names.", "| proposed name | canonical |\n|---|---|"),
        "Conflicts": ("Pairs that look like duplicates but are genuinely different mechanisms, "
                      "deliberately kept apart.", "| move A | move B | how to tell them apart |\n|---|---|---|"),
        "Dropped": ("Proposals too vague to parameterise, and why. Recorded so they are not "
                    "re-proposed.", "| proposal | why |\n|---|---|"),
    }

    primitives = carried_sections()
    out = [
        HEADER,
        "# Part 1 — primitives\n\nThe base vocabulary, carried unchanged from the original "
        "`MOVE_VOCAB.md`. These are the building blocks; the pattern families in Part 2 are "
        "compositions of them.\n",
        primitives,
        "\n",
        built_index(),
        "\n---\n",
        "# Part 2 — pattern families\n\nGrouped to match `PATTERNS.md` §1. These are recurring "
        "compositional patterns observed across the reference corpus, not primitives.\n",
        "\n\n".join(bodies),
        "\n---\n",
    ]
    for name in SECTIONS:
        rows = merged[name]
        if not rows:
            continue
        blurb, header = heads[name]
        out.append(f"## {name}\n\n{blurb}\n\n{header}\n" + "\n".join(rows) + "\n")

    OUT.write_text("\n".join(out))

    # count moves in the FAMILY tables only — alias and conflict rows also begin
    # with a backticked name and were inflating the total
    family_text = "\n\n".join(bodies)
    prim_moves = len(re.findall(r"^\|\s*`[a-zA-Z]", primitives, re.M))
    moves = len(re.findall(r"^\|\s*`[a-zA-Z]", family_text, re.M))
    built = len(re.findall(r"built:\s*[A-Z]", family_text))
    families = len(re.findall(r"^## \d+\.\d+", family_text, re.M))
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  parts merged     {len(PARTS)}/4")
    print(f"  families         {families}/12")
    print(f"  primitives       {prim_moves} (carried verbatim)")
    print(f"  family moves     ~{moves}  ({built} built, {moves - built} spec-only)")
    print(f"  total            ~{prim_moves + moves}")
    for name in SECTIONS:
        print(f"  {name.lower():<16} {len(merged[name])}")


if __name__ == "__main__":
    main()
